// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdvebplugvvhrzigtaxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkdmVicGx1Z3Z2aHJ6aWd0YXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjI2NzMsImV4cCI6MjA2NjUzODY3M30.ZFOFKXTXSm4Ps3kWrrtJYXLosRUsq7DISB0HAV9TB4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);